# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
script:
- set -o pipefail && xcodebuild test -workspace Mirror.xcworkspace -scheme Mirror -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --quick
