# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2
script:
- set -o pipefail && xcodebuild test -workspace Mirror.xcworkspace -scheme Mirror -sdk iphonesimulator -destination platform='iOS Simulator',OS='9.2',name='iPhone 6' ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
